spring:
  profiles:
    active: git
  config:
    import: "configserver:"
  application:
    name: equipment-service
  cloud:
    config:
      uri: http://localhost:8888

logging:
  level:
    org.springframework: INFO
    org.springframework.security: WARN
    org.springframework.data.mongodb: WARN

management:
  endpoints:
    web:
      exposure:
        include: "*"